config/routes.rb
Rails.application.routes.draw do
  get 'public_entities/user_location'
  get 'public_entities/entity_location/:public_entity_id', to: 'public_entities#entity_location'
  
  resources :public_entities
  root 'public_entities#index'
  
  resources :posts
  get 'posts/new'
  
  resources :categories
  get 'categories/index'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :installs
  

end

app/models/public_entity.rb
class PublicEntity
  #postgresql
  #has_many :posts
  #has_and_belongs_to_many :categories
  #has_many :subordinates, class_name: "PublicEntity", :foreign_key => "superior_id"
  #belongs_to :superior, class_name: "PublicEntity"
  include Mongoid::Document
  include Mongoid::Timestamps
  include Geocoder::Model::Mongoid
  include ::AlgoliaSearch
  algoliasearch do
    attribute :name, :description, :address
  end
  field :name
  field :authority_level
  field :address
  field :description
  field :website
  field :email_address
  field :entity_type
  field :superior_id
  field :phone
  field :coordinates, :type => Array
  field :source
  field :source_accessed
  field :hours, :type => Hash
  field :twitter_account
  has_many :chiefs
  has_and_belongs_to_many :categories
  has_many :posts
  has_many :subordinates, class_name: "PublicEntity", :foreign_key => "superior_id"
  belongs_to :superior, class_name: "PublicEntity"
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/controllers/public_entities_controller.rb
class PublicEntitiesController < ApplicationController
  def index
    @public_entities = PublicEntity.all
    @categories = Category.all
    @posts = Post.all
    @nyc_executives = PublicEntity.where(entity_type: 'city executive')
    @nyc_agencies = PublicEntity.where(authority_level: 'city', entity_type: 'agency')
    @nyc_subway_stations = PublicEntity.where(entity_type: 'subway_station')
    @nyc_post_offices = PublicEntity.where(entity_type: 'post_office')
    @nystate_agencies = PublicEntity.where(authority_level: 'state', entity_type: 'agency')
    @nystate_parks = PublicEntity.where(entity_type: 'park')
    @ten_most_recent_posts = Post.order_by(:created_at => 'desc').limit(10)
    @dmvs = PublicEntity.where(entity_type: 'DMV')
  end
  
  def user_location
    if current_user != nil
      render json: current_user.to_coordinates
    end
  end
  
  def entity_location
    if PublicEntity.find_by(params[:id]) != nil
      render json: PublicEntity.find_by(params[:id]).to_coordinates
    end
  end
  
  def show
    @post = Post.new
    @public_entity = PublicEntity.find(params[:id])
    @posts = PublicEntity.find(params[:id]).posts.order_by(:created_at => 'desc')
    @categories = PublicEntity.find(params[:id]).categories
    @subordinates = PublicEntity.find(params[:id]).subordinates
    @public_entity_coordinates = PublicEntity.find(params[:id]).to_coordinates
  end

end

app/helpers/public_entities_helper.rb
module PublicEntitiesHelper
end

app/views/public_entities/index.html.erb
<% provide(:title, "Our Government | Our Experiences") %>
<span class="logo"><%= link_to (image_tag "OurGov_Logo3.png", height: 'auto', width: '100%'), "/" %></span>

<script type="text/javascript">
$(document).ready(function(){
	$.each(['categories', 'nyc_executives', 'city_agencies', 'subways', 'post_offices', 'state_agencies', 'state_parks', 'dmv'], function(index, cssName){
		var list = $('.'+cssName+'_list');
		$(list).hide();
		$('.'+cssName).click(function(){
			$(list).slideToggle('slow');
		});
	});
});
</script>

<style type="text/css">
  html { height: 100% }
  body { height: 100%; margin: 0; padding: 0 }
  #map-canvas { height: 100% }
</style>

<script type="text/javascript">
  function test() {
    console.log('test() called');
  }

	function initialize() {
		//var marker = new google.maps.Marker({
	  //    position: new google.maps.LatLng(40.716593, -74.010593),
	  //    map: map,
	  //    title: 'My old house!'
    //});
    var map;

    $.get('public_entities/user_location', test);

    $.get('public_entities/user_location', function(data) {
      var userLatLng = data;
      console.log(userLatLng);

      // setup the map options (center it according to the user lat lng)x
	    var mapOptions = {
        //center: { lat: 40.725968, lng: -73.997667},
        center: { lat: userLatLng[0], lng: userLatLng[1]},
        zoom: 12
	    };

      // create the map
	    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
	
      // add a marker for our current location
      var marker = new google.maps.Marker({
        position: new google.maps.LatLng(userLatLng[0], userLatLng[1]),
        map: map,
        title: 'User!'
      });
    });

    //$.ajax(
    //  url: userLocUrl,
    //  success: function(res){
    //    console.log(res);
    //  },
    //  complete: function(){
    //    console.log("complete");
    //  }
    //);
		//var userLatLng = $.getJSON(userLocUrl, { format: 'json' })
	  }
	  google.maps.event.addDomListener(window, 'load', initialize);
</script>

<!--
<div id="map-canvas" style="width: 100%; height: 400px; display:inline-block"></div>
-->

<body>
  <div class="home-page-description">OurGov is a digital platform to report problems to and leave feedback for government services and agencies.</div>
  
<script src="//cdn.jsdelivr.net/jquery/2.1.3/jquery.min.js"></script>
<script src="//cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"></script>

<div class="search-box">
  <div class="search">
   	<input id="searchInput" type="text" />
    
    <script>
    $(document).ready(function() {
      var $input = $('input#searchInput');
      $input.focus();
      $input.keyup(function() {
        PublicEntityIndex.search($input.val(), {
          hitsPerPage: 10,
          facets: '*'
        }, searchCallback);
      });
    });

    function searchCallback(err, content) {
      if (err) {
        console.error(err);
        return;
      }
      
      var $results = $('#results');
      $results.empty();

      for (var i = 0; i < content.hits.length; i++) {
        $link = $('<a href="/public_entities/' + content.hits[i].objectID + '">' + content.hits[i].name + '</a>');
        $li = $('<li></li>');
        $li.append($link);
        $results.append($li);
      }
    };
    </script>
  </div>
  <div class="results">
    <ul id="results"></ul>
  </div>
</div>

<div class="index-category-links">
  <%= @categories.map { |category| link_to(category.name, category_path(category), 'data-no-turbolink' => true) }.join(' | ').html_safe %>
</div>

<!--
<table class="nav_buttons">
	<tr class="row">
		<td><span class="bracket">[ </span><%= link_to "DMVs", category_path(Category.find_by(name:'DMV')), 'data-no-turbolink' => true %><span class="bracket"> ]</span>
		</td>
		<td><span class="bracket">[ </span><%= link_to "Post Offices", category_path('Post Office'), 'data-no-turbolink' => true %><span class="bracket"> ]
		</td>
		<td><span class="bracket">[ </span>Parks & Rec<span class="bracket"> ]
		</td>
		<td><span class="bracket">[ </span>Police & Fire Services<span class="bracket"> ]
		</td>
	</tr>
	<tr class="row">
		<td><span class="bracket">[ </span>City & State Agencies<span class="bracket"> ]
		</td>
		<td><span class="bracket">[ </span><%= link_to "Subways & MTA", category_path("Subway Stations"), 'data-no-turbolink' => true %><span class="bracket"> ]
		</td>
		<td><span class="bracket">[ </span>Public Officials<span class="bracket"> ]
		</td>
		<td><span class="bracket">[ </span>Schools<span class="bracket"> ]
		</td>
	</tr>
</table>
--!>

<!--<h3 class="categories">Browse by Category</h3>
<ul>
	<% @categories.each do |category| %>
		<li class="categories_list"><%= link_to category.name, category_path(category) %></li>
	<% end %>
</ul>

<h3 class="nyc_executives">NYC Executive Officers</h3>
<ul><% @nyc_executives.each do |entity| %>
	<div class="nyc_executives_list"><%=link_to entity.name, public_entity_url(entity), 'data-no-turbolink' => true %></div>
	<%end%>
</ul>

<h3 class="city_agencies">NYC Agencies</h3>
<ul><% @nyc_agencies.each do |entity| %>
	<div class="city_agencies_list"><%=link_to entity.name, public_entity_url(entity), 'data-no-turbolink' => true %></div>
	<%end%>
</ul>

<h3 class="subways">NYC Subway Stations</h3>
<ul><% @nyc_subway_stations.each do |entity| %>
	<div class="subways_list"><%=link_to entity.name, public_entity_url(entity), 'data-no-turbolink' => true %></div>
	<%end%>
</ul>

<h3 class="post_offices">NYC Post Offices</h3>
<ul><% @nyc_post_offices.each do |entity| %>
	<div class="post_offices_list"><%=link_to entity.name, public_entity_url(entity), 'data-no-turbolink' => true %></div>
	<%end%>
</ul>

<h3 class="state_agencies">NY State Agencies</h3>
<ul><% @nystate_agencies.each do |entity| %>
	<div class="state_agencies_list"><%=link_to entity.name, public_entity_url(entity), 'data-no-turbolink' => true %></div>
	<%end%>
</ul>

<h3 class="state_parks">NY State Parks</h3>
<ul><% @nystate_parks.each do |entity| %>
	<div class="state_parks_list"><%=link_to entity.name, public_entity_url(entity), 'data-no-turbolink' => true %></div>
	<%end%>
</ul>

<h3 class="dmv">DMVs</h3>
<ul><% @dmvs.each do |entity| %>
	<div class="dmv_list"><%=link_to entity.name, public_entity_url(entity), 'data-no-turbolink' => true %></div>
	<%end%>
</ul>
-->
</body>

app/views/public_entities/show.html.erb
<% provide(:title, @public_entity.name + " - Leave a review!") %>

<script type="text/javascript">
	function initialize() {
	    var mapOptions = {
			center: { lat: 40.725968, lng: -73.997667}, zoom: 14
	    };
	    var map = new google.maps.Map(document.getElementById('map-canvas'),
	        mapOptions);
	  }
	  google.maps.event.addDomListener(window, 'load', initialize);
</script>

<div>[ Entity lat/lng: <%= @public_entity.to_coordinates %> ]</div>

<body>
  <div class="entity-show-page">
    <div class="show-page-sidebar">
      <div id="map-canvas"></div>
  		<div class="incumbents-info"><% @public_entity.chiefs.each do |chief| %>
  			<div><%= chief.title %>: <%= chief.name %></div>
  			<% if chief.salary != nil %>
  			<div>Salary: $<%= chief.salary %></div>
  			<% end %>
  			<div><%= chief.election_info %></div>
  			<% end %>
  		</div>
    </div>
	<div class="entity-info">
		<div class="entity-name"><%= link_to @public_entity.name, @public_entity, 'data-no-turbolink' => true %></div>
		<div class="entity-categories"><%= @categories.map { |category| link_to(category.name, category_path(category), 'data-no-turbolink' => true) }.join(' | ').html_safe %>
		</div>
			<div class="entity-basic-info">
        <div><%= @public_entity.phone %></div>
  			<div><%= @public_entity.address %></div>
  			<div><% if @public_entity.website != nil %>
  				<%= link_to @public_entity.website, @public_entity.website, 'data-no-turbolink' => true %>
  				<% end %>
  			</div>
      </div>
			<div class="superior"><% if @public_entity.superior != nil %>
				This entity reports to the <%= link_to @public_entity.superior.name, @public_entity.superior, 'data-no-turbolink' => true %>
				<% end %>
			</div>
      <div class="entity-description"><%= @public_entity.description %></div>
			<div class="subordinates"><% if @subordinates.empty? == false %>
				<div>The following entities report to this office:</div>
				<%= @subordinates.map { |subordinate| link_to(subordinate.name, public_entity_path(subordinate), 'data-no-turbolink' => true) }.join(' | ').html_safe %>
				<% end %>
			</div>
    </div>

		<div class="leave-review">
			<div class="form-inputs">
        <div>Write a review!</div>
				<%= form_for @post, :url => {:controller => "posts", :action => "create" } do |f| %>
				    <%= f.hidden_field :public_entity_id, value: @public_entity.id %>
				     <%= f.text_field :rating, class: "form-field", placeholder: "Please give a rating on a scale from 1-5" %>
				     <%= f.text_area :review, class: "form-field", rows: 4, placeholder: "Start your review..." %>
             <%= f.submit "Submit your review", class: "submit-button"%>
				<% end %>
			</div>
		</div>

		<div class="review">
      <div class="review-count">There are <strong><%= @posts.count %></strong> reviews.</div>
      <% @posts.each do |post| %>
			  <div class="review-date">On <%= post.created_at.time.strftime("%m/%d/%y") %></div>
			  <div class="review-name"> <%= post.user.first_name.to_s + ' ' + post.user.last_name[0].to_s %>.</div>
			  <div class="review-text">left a review:</div>
			  <div class="review-rating"><%= post.rating %> Stars!</div>
			  <div class="review-content"><%= post.review %></div>
		<% end %>
		</div>
  </div>
</body>