config/routes.rb
Rails.application.routes.draw do
  get 'public_entities/user_location'
  get 'public_entities/entity_location/:public_entity_id', to: 'public_entities#entity_location'
  
  resources :public_entities
  root 'public_entities#index'
  
  resources :posts
  get 'posts/new'
  
  resources :categories
  get 'categories/index'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :installs
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%=yield (:title)%></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <p class="notice"><%= notice %></p>
	  <p class="alert"><%= alert %></p>
	  <meta name="google-site-verification" content="bBOPecKMVOFAuWWEn2AQPLGpS3udX_NWkxHqJSroZVA" />
	  <script type="text/javascript"
	  src=<%="https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_API_KEY']}"%>>
	  </script>
	  <script src="//cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"></script>
	  <script>
	    var client = algoliasearch("75W7HLBU2C", "ae0d5cd176b28df1789768374f4e74b1"); // public credentials
	    var PublicEntityIndex = client.initIndex('PublicEntity');
      var CategoriesIndex = client.initIndex('Category');
      var ChiefsIndex = client.initIndex('Chief');
	  </script>
	</head>
	<body>
		<header class="header">
			<span class="header-name"><%= link_to "OurGov", public_entities_path, 'data-no-turbolink' => true %></span>
			<span class="header-text"><%= link_to "Home", public_entities_path, 'data-no-turbolink' => true %>
			<% if user_signed_in? == false %>
			&nbsp<%= link_to "Sign Up", new_user_registration_path %>
			&nbsp<%= link_to "Log In", new_user_session_path %>
			<% end %>
			<% if user_signed_in? == true %>
			&nbsp<%= link_to "Profile", edit_user_registration_path %>
			&nbsp<%= link_to "Log Out", destroy_user_session_path, :method => :delete %>
			<% end %></span>
			</div>
		</header>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>